import type { Metadata } from "next";
import { Nanum_Pen_Script } from "next/font/google";
import "@/app/ui/globals.css";

const font = Nanum_Pen_Script({
  subsets: ["latin"],
  display: "swap",
  weight: `400`,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
